import type { Product, Category, PaymentMethod } from '../types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Pain Relief',
    description: 'Medications for pain management',
    image_url: '/first-aid.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Fever & Cold',
    description: 'Medications for fever and cold symptoms',
    image_url: '/blood.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Vitamins & Supplements',
    description: 'Essential vitamins and dietary supplements',
    image_url: '/vaccination.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'First Aid',
    description: 'First aid supplies and bandages',
    image_url: '/first-aid.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Prescription Drugs',
    description: 'Medications requiring prescription',
    image_url: '/blood.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    description: 'Effective pain reliever and fever reducer. Suitable for adults and children over 12 years.',
    price: 25.00,
    originalPrice: 35.00,
    category: 'Pain Relief',
    subcategory: 'Analgesics',
    images: ['/first-aid.jpg'],
    composition: 'Paracetamol 500mg',
    dosage: '1-2 tablets every 4-6 hours as needed',
    manufacturer: 'ABC Pharmaceuticals',
    prescription_required: false,
    stock_quantity: 150,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Ibuprofen 400mg',
    description: 'Anti-inflammatory pain reliever for headaches, muscle pain, and inflammation.',
    price: 45.00,
    originalPrice: 55.00,
    category: 'Pain Relief',
    subcategory: 'NSAIDs',
    images: ['/blood.jpg'],
    composition: 'Ibuprofen 400mg',
    dosage: '1 tablet every 6-8 hours with food',
    manufacturer: 'XYZ Pharma',
    prescription_required: false,
    stock_quantity: 100,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Vitamin C 1000mg',
    description: 'High potency Vitamin C supplement for immune system support.',
    price: 120.00,
    originalPrice: 150.00,
    category: 'Vitamins & Supplements',
    subcategory: 'Vitamins',
    images: ['/vaccination.jpg'],
    composition: 'Ascorbic Acid 1000mg',
    dosage: '1 tablet daily with meals',
    manufacturer: 'Health Plus',
    prescription_required: false,
    stock_quantity: 200,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Cetirizine 10mg',
    description: 'Antihistamine for allergy relief and hay fever symptoms.',
    price: 35.00,
    originalPrice: 45.00,
    category: 'Fever & Cold',
    subcategory: 'Antihistamines',
    images: ['/first-aid.jpg'],
    composition: 'Cetirizine Hydrochloride 10mg',
    dosage: '1 tablet daily',
    manufacturer: 'Allergy Care',
    prescription_required: false,
    stock_quantity: 80,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Bandage Roll 3 inch',
    description: 'Sterile gauze bandage for wound dressing and first aid.',
    price: 15.00,
    originalPrice: 20.00,
    category: 'First Aid',
    subcategory: 'Bandages',
    images: ['/blood.jpg'],
    composition: 'Sterile cotton gauze',
    dosage: 'As needed for wound dressing',
    manufacturer: 'First Aid Pro',
    prescription_required: false,
    stock_quantity: 300,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Amoxicillin 500mg',
    description: 'Antibiotic for bacterial infections. Requires prescription.',
    price: 85.00,
    originalPrice: 95.00,
    category: 'Prescription Drugs',
    subcategory: 'Antibiotics',
    images: ['/vaccination.jpg'],
    composition: 'Amoxicillin Trihydrate 500mg',
    dosage: '1 capsule 3 times daily as prescribed',
    manufacturer: 'MediCare',
    prescription_required: true,
    stock_quantity: 50,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Vitamin D3 1000IU',
    description: 'Essential vitamin for bone health and immune function.',
    price: 95.00,
    originalPrice: 120.00,
    category: 'Vitamins & Supplements',
    subcategory: 'Vitamins',
    images: ['/first-aid.jpg'],
    composition: 'Cholecalciferol 1000IU',
    dosage: '1 tablet daily with fatty meal',
    manufacturer: 'NutriHealth',
    prescription_required: false,
    stock_quantity: 120,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Aspirin 100mg',
    description: 'Low-dose aspirin for heart health and pain relief.',
    price: 30.00,
    originalPrice: 40.00,
    category: 'Pain Relief',
    subcategory: 'Analgesics',
    images: ['/blood.jpg'],
    composition: 'Acetylsalicylic Acid 100mg',
    dosage: '1 tablet daily as prescribed',
    manufacturer: 'HeartCare Pharma',
    prescription_required: false,
    stock_quantity: 200,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: '1',
    type: 'cod',
    name: 'Cash on Delivery',
    description: 'Pay when you receive your order',
    is_active: true,
  },
  {
    id: '2',
    type: 'card',
    name: 'Credit/Debit Card',
    description: 'Secure payment via card',
    is_active: true,
  },
  {
    id: '3',
    type: 'upi',
    name: 'UPI Payment',
    description: 'Quick payment via UPI',
    is_active: true,
  },
];

export const featuredProducts = mockProducts.filter(product => product.is_featured);
export const categoriesWithProducts = mockCategories.map(category => ({
  ...category,
  products: mockProducts.filter(product => product.category === category.name),
})); 